import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportCSV(investigations) {

    const headers = [
        "ID",
        "Product",
        "Violation",
        "Risk Score",
        "Category",
        "Created"
    ];

    const rows = investigations.map(i => [

        i.id,

        i.title,

        i.violation,

        i.risk_score,

        i.risk_category,

        i.created_at

    ]);

    const csv = [

        headers.join(","),

        ...rows.map(r => r.join(","))

    ].join("\n");

    const blob = new Blob([csv], {

        type: "text/csv"

    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;

    a.download = "investigations.csv";

    a.click();

    URL.revokeObjectURL(url);

}

export const exportPDF = (investigations) => {

    const doc = new jsPDF();

    // ----------------------------
    // Header
    // ----------------------------

    doc.setFontSize(22);
    doc.setTextColor(33, 150, 243);
    doc.text("TrustLens AI", 14, 20);

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Investigation Report", 14, 30);

    doc.setFontSize(10);
    doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        14,
        38
    );

    // ----------------------------
    // Summary
    // ----------------------------

    const violations =
        investigations.filter(i => i.violation).length;

    const avgRisk =
        investigations.length === 0
            ? 0
            : Math.round(
                investigations.reduce(
                    (sum, i) => sum + i.risk_score,
                    0
                ) / investigations.length
            );

    doc.setFontSize(13);

    doc.text("Summary", 14, 52);

    doc.setFontSize(11);

    doc.text(
        `Total Investigations : ${investigations.length}`,
        14,
        60
    );

    doc.text(
        `Violations : ${violations}`,
        14,
        68
    );

    doc.text(
        `Average Risk : ${avgRisk}`,
        14,
        76
    );

    // ----------------------------
    // Table
    // ----------------------------

    autoTable(doc, {

        startY: 88,

        head: [[
            "ID",
            "Product",
            "Violation",
            "Risk",
            "Category",
            "Created"
        ]],

        body: investigations.map(i => [

            i.id,

            i.product_title,

            i.violation ? "YES" : "NO",

            i.risk_score,

            i.category,

            new Date(i.created_at).toLocaleString()

        ])

    });

    // ----------------------------
    // Footer
    // ----------------------------

    const finalY =
        doc.lastAutoTable.finalY + 12;

    doc.setFontSize(10);

    doc.text(
        "Generated by TrustLens AI",
        14,
        finalY
    );

    doc.save("trustlens-investigations.pdf");

};